[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "2QaArRLt7zTe3orXxpv1Epx9v5a4Ga9KbCp5655QbCtg"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
