[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tip_jar = "2jUpd4u5nk14oiLmBpVskm9SES38W4khomHxeQp2HSuU"

[programs.devnet]
tip_jar = "2jUpd4u5nk14oiLmBpVskm9SES38W4khomHxeQp2HSuU"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
