[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_marketplace = "DPZVLmiip36N4TnJBghu7opiZTBx6C4LBH4j9WhRPEpN"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
